//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobusRemote.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobusRemote.Localize.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в систему.
        /// </summary>
        public static string AccountPage_Login_Title {
            get {
                return ResourceManager.GetString("AccountPage_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация не выполнена: неверный логин или пароль..
        /// </summary>
        public static string ActionLogin_Alert_Failed {
            get {
                return ResourceManager.GetString("ActionLogin_Alert_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация успешно завершена..
        /// </summary>
        public static string ActionLogin_Alert_Successed {
            get {
                return ResourceManager.GetString("ActionLogin_Alert_Successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операторы.
        /// </summary>
        public static string AdminPage_Operators_Title {
            get {
                return ResourceManager.GetString("AdminPage_Operators_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны операторов.
        /// </summary>
        public static string AdminPage_OperatorsTemplates_Title {
            get {
                return ResourceManager.GetString("AdminPage_OperatorsTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        public static string AdminPage_Title {
            get {
                return ResourceManager.GetString("AdminPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobusRemote.
        /// </summary>
        public static string Base_AppName {
            get {
                return ResourceManager.GetString("Base_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите элемент....
        /// </summary>
        public static string DataControl_DropDownList_Select_Title {
            get {
                return ResourceManager.GetString("DataControl_DropDownList_Select_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string DataControl_File_Confirm_Title {
            get {
                return ResourceManager.GetString("DataControl_File_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл....
        /// </summary>
        public static string DataControl_File_Select_Title {
            get {
                return ResourceManager.GetString("DataControl_File_Select_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новую запись.
        /// </summary>
        public static string DataControl_Submit_Add_Hint {
            get {
                return ResourceManager.GetString("DataControl_Submit_Add_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string DataControl_Submit_Add_Title {
            get {
                return ResourceManager.GetString("DataControl_Submit_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить выбранную запись?.
        /// </summary>
        public static string DataControl_Submit_Delete_Confirm {
            get {
                return ResourceManager.GetString("DataControl_Submit_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить текущую запись.
        /// </summary>
        public static string DataControl_Submit_Delete_Hint {
            get {
                return ResourceManager.GetString("DataControl_Submit_Delete_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DataControl_Submit_Delete_Title {
            get {
                return ResourceManager.GetString("DataControl_Submit_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать текущую запись.
        /// </summary>
        public static string DataControl_Submit_Edit_Hint {
            get {
                return ResourceManager.GetString("DataControl_Submit_Edit_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string DataControl_Submit_Edit_Title {
            get {
                return ResourceManager.GetString("DataControl_Submit_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string DataControl_Submit_Search_Clear_Title {
            get {
                return ResourceManager.GetString("DataControl_Submit_Search_Clear_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка поиска.
        /// </summary>
        public static string DataControl_Submit_Search_Field_Title {
            get {
                return ResourceManager.GetString("DataControl_Submit_Search_Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Искать.
        /// </summary>
        public static string DataControl_Submit_Search_Title {
            get {
                return ResourceManager.GetString("DataControl_Submit_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотреть содержимое текущей записи.
        /// </summary>
        public static string DataControl_Submit_Show_Hint {
            get {
                return ResourceManager.GetString("DataControl_Submit_Show_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string DataControl_Submit_Show_Title {
            get {
                return ResourceManager.GetString("DataControl_Submit_Show_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string DialogBase_Submit_Close {
            get {
                return ResourceManager.GetString("DialogBase_Submit_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string DialogEdit_Submit_Title {
            get {
                return ResourceManager.GetString("DialogEdit_Submit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string DialogLogin_Submit_Title {
            get {
                return ResourceManager.GetString("DialogLogin_Submit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используйте локальную учетную запись для входа в систему..
        /// </summary>
        public static string DialogLogin_Text {
            get {
                return ResourceManager.GetString("DialogLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл с указанным именем уже существует..
        /// </summary>
        public static string Error_DB_UK_RSAppFiles_Name {
            get {
                return ResourceManager.GetString("Error_DB_UK_RSAppFiles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренний код.
        /// </summary>
        public static string Field_Base_Code {
            get {
                return ResourceManager.GetString("Field_Base_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код ответа.
        /// </summary>
        public static string Field_Base_CodeResponse {
            get {
                return ResourceManager.GetString("Field_Base_CodeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Field_Base_Comment {
            get {
                return ResourceManager.GetString("Field_Base_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string Field_Base_Date {
            get {
                return ResourceManager.GetString("Field_Base_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата изменения.
        /// </summary>
        public static string Field_Base_DateChanged {
            get {
                return ResourceManager.GetString("Field_Base_DateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string Field_Base_DateCreated {
            get {
                return ResourceManager.GetString("Field_Base_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окончание.
        /// </summary>
        public static string Field_Base_DateFinish {
            get {
                return ResourceManager.GetString("Field_Base_DateFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string Field_Base_DateStart {
            get {
                return ResourceManager.GetString("Field_Base_DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение.
        /// </summary>
        public static string Field_Base_Extention {
            get {
                return ResourceManager.GetString("Field_Base_Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ.
        /// </summary>
        public static string Field_Base_FlagAdmin {
            get {
                return ResourceManager.GetString("Field_Base_FlagAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее.
        /// </summary>
        public static string Field_Base_FlagCurrent {
            get {
                return ResourceManager.GetString("Field_Base_FlagCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию.
        /// </summary>
        public static string Field_Base_FlagDefault {
            get {
                return ResourceManager.GetString("Field_Base_FlagDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не используется.
        /// </summary>
        public static string Field_Base_FlagExpire {
            get {
                return ResourceManager.GetString("Field_Base_FlagExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующее.
        /// </summary>
        public static string Field_Base_FlagNext {
            get {
                return ResourceManager.GetString("Field_Base_FlagNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        public static string Field_Base_Group {
            get {
                return ResourceManager.GetString("Field_Base_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string Field_Base_Id {
            get {
                return ResourceManager.GetString("Field_Base_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Field_Base_Lang {
            get {
                return ResourceManager.GetString("Field_Base_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Field_Base_Login {
            get {
                return ResourceManager.GetString("Field_Base_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Field_Base_Name {
            get {
                return ResourceManager.GetString("Field_Base_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        public static string Field_Base_Operations {
            get {
                return ResourceManager.GetString("Field_Base_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принадлежность.
        /// </summary>
        public static string Field_Base_ParentLink {
            get {
                return ResourceManager.GetString("Field_Base_ParentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Field_Base_Password {
            get {
                return ResourceManager.GetString("Field_Base_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        public static string Field_Base_Phone {
            get {
                return ResourceManager.GetString("Field_Base_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сценарий.
        /// </summary>
        public static string Field_Base_ScenarioLink {
            get {
                return ResourceManager.GetString("Field_Base_ScenarioLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер, кб.
        /// </summary>
        public static string Field_Base_Size {
            get {
                return ResourceManager.GetString("Field_Base_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Field_Base_Text {
            get {
                return ResourceManager.GetString("Field_Base_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Field_Base_Type {
            get {
                return ResourceManager.GetString("Field_Base_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не может быть длиннее.
        /// </summary>
        public static string FieldValidate_Max_Title1 {
            get {
                return ResourceManager.GetString("FieldValidate_Max_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to символов..
        /// </summary>
        public static string FieldValidate_Max_Title2 {
            get {
                return ResourceManager.GetString("FieldValidate_Max_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не заполнено..
        /// </summary>
        public static string FieldValidate_Required_Title {
            get {
                return ResourceManager.GetString("FieldValidate_Required_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APS - Международный грузоперевозчик.
        /// </summary>
        public static string Footer_Company_Title {
            get {
                return ResourceManager.GetString("Footer_Company_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://aps-solver.ru/.
        /// </summary>
        public static string Footer_Company_Url {
            get {
                return ResourceManager.GetString("Footer_Company_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные.
        /// </summary>
        public static string Header_General {
            get {
                return ResourceManager.GetString("Header_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string Header_Login {
            get {
                return ResourceManager.GetString("Header_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Header_Logout {
            get {
                return ResourceManager.GetString("Header_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Header_Main {
            get {
                return ResourceManager.GetString("Header_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globus Mobile.
        /// </summary>
        public static string Header_Mobile {
            get {
                return ResourceManager.GetString("Header_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для входа в систему нужно .
        /// </summary>
        public static string HomePage_Body_Auth_Text1 {
            get {
                return ResourceManager.GetString("HomePage_Body_Auth_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to авторизироваться.
        /// </summary>
        public static string HomePage_Body_Auth_Text2 {
            get {
                return ResourceManager.GetString("HomePage_Body_Auth_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string HomePage_Body_Auth_Text3 {
            get {
                return ResourceManager.GetString("HomePage_Body_Auth_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string HomePage_Body_Title {
            get {
                return ResourceManager.GetString("HomePage_Body_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная страница.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string MobileBooksPage_Contacts_Title {
            get {
                return ResourceManager.GetString("MobileBooksPage_Contacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл - добавление.
        /// </summary>
        public static string MobileBooksPage_Files_Add_Title {
            get {
                return ResourceManager.GetString("MobileBooksPage_Files_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл - редактирование.
        /// </summary>
        public static string MobileBooksPage_Files_Edit_Title {
            get {
                return ResourceManager.GetString("MobileBooksPage_Files_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы.
        /// </summary>
        public static string MobileBooksPage_Files_Title {
            get {
                return ResourceManager.GetString("MobileBooksPage_Files_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочники.
        /// </summary>
        public static string MobileBooksPage_Title {
            get {
                return ResourceManager.GetString("MobileBooksPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобил. приложения.
        /// </summary>
        public static string MobilePage_Title {
            get {
                return ResourceManager.GetString("MobilePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string MobilePage_Users_Title {
            get {
                return ResourceManager.GetString("MobilePage_Users_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string MobilePage_UsersContacts_Title {
            get {
                return ResourceManager.GetString("MobilePage_UsersContacts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        public static string MobilePage_UsersMessages_Title {
            get {
                return ResourceManager.GetString("MobilePage_UsersMessages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Командировки.
        /// </summary>
        public static string MobilePage_UsersMissions_Title {
            get {
                return ResourceManager.GetString("MobilePage_UsersMissions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны.
        /// </summary>
        public static string MobilePage_UsersTemplates_Title {
            get {
                return ResourceManager.GetString("MobilePage_UsersTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сценарии.
        /// </summary>
        public static string MobileScenariosPage_Scenarios_Title {
            get {
                return ResourceManager.GetString("MobileScenariosPage_Scenarios_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия сценариев.
        /// </summary>
        public static string MobileScenariosPage_ScenariosActions_Title {
            get {
                return ResourceManager.GetString("MobileScenariosPage_ScenariosActions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наборы сценариев.
        /// </summary>
        public static string MobileScenariosPage_ScenariosGroups_Title {
            get {
                return ResourceManager.GetString("MobileScenariosPage_ScenariosGroups_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны сценариев.
        /// </summary>
        public static string MobileScenariosPage_Title {
            get {
                return ResourceManager.GetString("MobileScenariosPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите сюда файл..
        /// </summary>
        public static string Service_File_Drag_Title {
            get {
                return ResourceManager.GetString("Service_File_Drag_Title", resourceCulture);
            }
        }
    }
}
